import React, { useState } from 'react';
import { Navbar } from './components/Navbar';
import { Hero } from './components/Hero';
import { ComplaintForm } from './components/ComplaintForm';
import { TrackingStatus } from './components/TrackingStatus';
import { LegalInfo } from './components/LegalInfo';
import { DataArchive } from './components/DataArchive';
import { PanicButton } from './components/PanicButton';
import { AppView, ComplaintData } from './types';
import { CheckCircle } from 'lucide-react';

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<AppView>(AppView.HOME);
  const [lastSubmissionId, setLastSubmissionId] = useState<string | null>(null);

  const handleComplaintSubmit = (data: any) => {
    // The data object now contains the real tracking ID from the store
    console.log("Submitting Complaint:", data);
    
    // Use the ID generated by the store
    setLastSubmissionId(data.trackingId);
  };

  const renderContent = () => {
    if (lastSubmissionId && currentView === AppView.COMPLAINT_FORM) {
      return (
        <div className="max-w-xl mx-auto mt-12 p-8 bg-white rounded-2xl shadow-xl text-center animate-fade-in">
          <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
            <CheckCircle className="w-10 h-10 text-green-600" />
          </div>
          <h2 className="text-3xl font-bold text-slate-900 mb-2">Complaint Filed</h2>
          <p className="text-slate-500 mb-6">Your report has been securely transmitted to the relevant district nodal officer.</p>
          
          <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 mb-8">
            <span className="block text-sm text-slate-500 mb-1">Your Tracking ID</span>
            <span className="block text-4xl font-mono font-bold text-indigo-600 tracking-wider select-all">{lastSubmissionId}</span>
            <p className="text-xs text-slate-400 mt-2">Please save this ID to track your status.</p>
          </div>

          <div className="flex gap-4 justify-center">
             <button 
               onClick={() => setCurrentView(AppView.TRACK_STATUS)}
               className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-indigo-700"
             >
               Track Status
             </button>
             <button 
               onClick={() => {
                 setLastSubmissionId(null);
                 setCurrentView(AppView.DATA_ARCHIVE);
               }}
               className="text-slate-600 px-6 py-2 hover:bg-slate-50 rounded-lg"
             >
               View Live Dashboard
             </button>
          </div>
        </div>
      );
    }

    switch (currentView) {
      case AppView.HOME:
        return <Hero onNavigate={setCurrentView} />;
      case AppView.COMPLAINT_FORM:
        return <ComplaintForm onSubmit={handleComplaintSubmit} onCancel={() => setCurrentView(AppView.HOME)} />;
      case AppView.TRACK_STATUS:
        return <TrackingStatus />;
      case AppView.LEGAL_INFO:
        return <LegalInfo />;
      case AppView.DATA_ARCHIVE:
        return <DataArchive />;
      default:
        return <Hero onNavigate={setCurrentView} />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      <Navbar onNavigate={(view) => {
        setLastSubmissionId(null); // Reset submission success view on nav
        setCurrentView(view);
      }} />
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 pt-6">
        {renderContent()}
      </main>
      <PanicButton />
      
      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-4 gap-8">
           <div>
             <h4 className="text-white font-bold mb-4">IDCP</h4>
             <p className="text-sm">
               National initiative to eradicate dowry through technology and transparency.
             </p>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Emergency</h4>
             <ul className="space-y-2 text-sm">
               <li>Police Control Room: 100</li>
               <li>Women Helpline: 1091</li>
               <li>Domestic Abuse: 181</li>
             </ul>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Legal</h4>
             <ul className="space-y-2 text-sm">
               <li>Privacy Policy</li>
               <li>Terms of Use</li>
               <li>IPC 498A Guidelines</li>
             </ul>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Contact Nodal Officer</h4>
             <p className="text-sm">helpdesk@idcp.gov.in</p>
             <p className="text-sm mt-2">New Delhi, India</p>
           </div>
        </div>
        <div className="text-center text-xs mt-12 pt-8 border-t border-slate-800">
           © 2024 India Dowry Complaint Portal. All rights reserved.
        </div>
      </footer>
    </div>
  );
};

export default App;